/**
 * The two ports the walkthrough pins, and the one address it cannot pin.
 *
 * Read by `playwright.config.ts` and by the walkthrough itself, so there is one
 * statement of where each process lives rather than two that can disagree.
 *
 * **The API's port is fixed and the reference agents' is not**, and the asymmetry is
 * the reason this file exists. Vite's proxy is configured at startup from
 * `AGENTAUDIT_API`, so the bench's address has to be known before either process
 * runs; the reference agents are bound by `serving.serve` on an ephemeral port, which
 * is what keeps a walkthrough from failing on a machine already using a chosen one.
 * So the agents' address is discovered rather than declared: `harness.py` writes it
 * beside this file once they are up, and Playwright will not start a test until the
 * harness answers.
 */

import { readFileSync } from 'node:fs'

/** Where the bench's API is served, and so what Vite proxies to. */
export const API_PORT = 8123

/** Where the app is served. Vite's default is left alone for a person's own `npm run dev`. */
export const APP_PORT = 5273

/** What `harness.py` reads its port from. Its own constant is the same string. */
export const API_PORT_VARIABLE = 'AGENTAUDIT_E2E_API_PORT'

/** The reference agent the walkthrough registers, as the harness left it. */
export interface ServedTarget {
  /** The endpoint typed into the registration form. */
  target_url: string
  /**
   * Where the nonce is planted.
   *
   * The reference agents' test-equipment route, which is how they take part in
   * registration like any other target — `nonce_planter` uses this same route on
   * every gate run. A user plants the value in their own system prompt by hand;
   * there is no other way in, and this walkthrough does not invent one.
   */
  plant_url: string
  /** What the served agents expect in `Authorization: Bearer …`. */
  auth_token: string
  /** The agent's name, which is what the report will call the target. */
  name: string
  /**
   * The public half of the key this bench signs with, for one run.
   *
   * Generated by the harness and never the committed one: a recipient checks an
   * artefact with `scripts/verify` against a key file, and the key this walkthrough's
   * bench holds is not the published key whose fingerprint the README carries. So the
   * walk verifies against the half of its own pair, which is the only key its report
   * can verify against (ADR-0017).
   */
  pubkey: string
}

/**
 * What the harness served, or a failure that says the harness is the thing to look at.
 *
 * Read at the moment it is needed rather than at import, because the file is written
 * by another process: a module-level read would be a race against the webServer
 * Playwright is still starting.
 */
export function servedTarget(): ServedTarget {
  const at = new URL('./served.json', import.meta.url)
  return JSON.parse(readFileSync(at, 'utf-8')) as ServedTarget
}
